Dbase
Code-the-Dream-School/MyKitchenApp-back pull request #13
Opened 2022-10-26 17:48 UTC by Dahlak76

## Description

added access to spoon API to get user queries  and for query by id
## Resouce links or research articles

## Related Issue
#11 #12

## Acceptance Criteria

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|    | :bug: Bug fix              |
|  ✓ | :sparkles: New feature     |
|    | :hammer: Refactoring       |
|    | :100: Add tests            |
|    | :link: Update dependencies |
|    | :scroll: Docs              |

## Updates

### Before

### After

## Testing Steps / QA Criteria

2022-10-27 02:26 UTC, jrmcgarvey requested changes
This is good, but the /api/v1/recipes routes should be moved to a file in the routes folder, and the logic in them should be moved to a file in the controllers folder.  We want to follow best practices in the organization of files from the start.

2022-10-27 19:25 UTC, CodergirlVS approved these changes
Awesome! looks good. Noted few changes, Once done we can merge the PR. Thanks

2022-10-27 19:25 UTC, CodergirlVS commented on app.js
> +//get recipe by query- combines searching by query, by ingredients, and by nutrients into one endpoint.
we will need one more route to get current user data

2022-10-27 19:31 UTC, CodergirlVS commented
In the PR Template for testing steps dont post the entire result. It should be short and just give some idea of the result. may be one sample object but dont make it too long. :))

2022-10-28 02:53 UTC, jrmcgarvey commented
> In the PR Template for testing steps dont post the entire result. It should be short and just give some idea of the result. may be one sample object but dont make it too long. :))

2022-10-28 03:01 UTC, jrmcgarvey commented
> In the PR Template for testing steps dont post the entire result. It should be short and just give some idea of the result. may be one sample object but dont make it too long. :))

Vaidehi, the first result posted is longer than it needs to be, because it is an array -- so we could just give a couple examples and then put ... .  But the second result, which is really long, is something we need to discuss.  Either this will have to be parsed on the front end, displaying the parts we care about, or we could parse it on the back end and just return a subset.  So this is a question for discussion.  I think we should leave the whole ugly thing in the PR for now until we know which parts we're going to remove from the API.  We may be able to shorten it some for that discussion, because there are arrays, e.g. for ingredients, which could be boiled down to just an example or two.  But there are also flags, and we need to keep them all documented so the front end can decide what to do with them.

2022-10-29 00:38 UTC, jrmcgarvey approved these changes
Ok, looks good now.

2022-10-29 00:38 UTC, merged